# Generated by Django 4.0.2 on 2022-02-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='', verbose_name='Текст комментария'),
        ),
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
